receivers:
  # Receiver 1.
  # <receiver type>:
  mizureceiver:
    # <setting one>: <value one>
    endpoint: host.docker.internal:8788
    # ...
service:
  pipelines:
    # Valid pipelines are: traces, metrics or logs
    # log pipeline 1.
    logs:
      receivers: [mizureceiver]
      processors: []
      # TODO - export to postgres via fluentd???
      exporters: [exampleexporter]
